version: "3.8"

services:
  agent-service:
    build:
      context: ./agent-service
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./agent-service/.env
    ports:
      - "3000:3000"
    depends_on:
      - transaction-service

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./transaction-service/.env
    ports:
      - "3001:3001"

networks:
  default:
    name: moga-backend-dev_default
    driver: bridge
